name: Engage Playwright Tests
on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * 1-5'
jobs:

  Engage-test:
    timeout-minutes: 150
    runs-on: 
      - self-hosted
      - JARVIS
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Navigating to the Engage playwright project, installing dependencies, and running tests
      run: 
        npm ci;
        npx playwright install --with-deps;
        npx playwright test --headed --workers 3;
        npm run create-allure-report


    - name: Upload artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
            ./playwright-report/*.html
            ./playwright-report/allure-report/*.html
        retention-days: 30
        

